# Generated by Django 4.2.7 on 2024-01-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newindexpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='newindexpage',
            name='intro',
        ),
    ]
