# Generated by Django 4.2.7 on 2024-01-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogindexpage_date_remove_blogindexpage_intro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
    ]
